---
title: "Bitcoin"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(forecast)
library(zoo)
library(lubridate)
```


```{r}
bitcoin <- read_csv("bitcoin data.csv") %>% janitor::clean_names()
```

```{r}
head(bitcoin)
```

```{r}
tail(bitcoin)
```


```{r}
bitcoin$date_time <- as_datetime(bitcoin$timestamp, tz = "US/Central")
bitcoin$date <- as_date(bitcoin$date_time)
```


```{r}
bitcoin <- bitcoin %>%
  filter(close != "NaN")

btc <- bitcoin %>%
  group_by(date) %>%
  summarise(daily_high = max(high),
            daily_low = min(low),
            daily_median = median(weighted_price),
            daily_mean = mean(weighted_price)) %>%
  distinct(date, .keep_all = T)
```



```{r}
btc_zoo <- read.zoo(btc, format = "%Y-%m-%d")
```

```{r}
btc_train <- window(btc_zoo, end = "2019-12-31")
btc_test <- window(btc_zoo, start =  "2019-12-31")

tail(btc_train)
```

```{r}
btc_arima <- auto.arima(btc_train$daily_mean)
```

```{r}
btc_pred <- forecast(btc_arima, h = nrow(btc_test))

btc_regress <- lm(daily_mean ~ date, data = btc) 

summary(btc_regress)
AIC(btc_regress)
```

